### ISSUE TITLE
Discussion about AV equipment for meetups

### ISSUE THREAD

**Issue by phenomnomnominal** [JavaScript-NZ/Society-Meetings#15] opened 2015-09-02 07:43 UTC
If we can get some decent gear we could sent it around the country like the NodeBots kits and we could stream (or at least record) talks at meetups etc.

**Comment by jenofdoom** [comment] 2015-12-09 07:16
Closing this because it's essentially a dupe of #33

**Closed as completed by jenofdoom** 2015-12-09 07:16 UTC
