### ISSUE TITLE
Discuss direction of NodeBots NZ

### ISSUE THREAD

**Issue by Unfocused** [JavaScript-NZ/Society-Meetings#26] opened 2015-10-19 12:23 UTC
Discuss what we should be doing and where we should be heading in the future.

**Comment by PrototypeAlex** [comment] 2015-10-27 06:57
Somewhat of a duplicate of the answer in https://github.com/JavaScript-NZ/Society-Meetings/issues/27#issuecomment-151396117

But in short:

We'll be focusing on developers/adults and students.
The gear that we get and what we do (nodeboats/rockets/etc) will be driven by attendees.
We're working on a bunch of resources that will make running an event easier, and attending an event more fun and educational.
And as usual, we'll be building up the kit and trying to get it run at more an more events.

**Closed as completed by PrototypeAlex** 2015-10-27 06:57 UTC
Labels: nodebots
